# Generated by Django 4.0.3 on 2022-03-21 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_category_remove_question_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='polls.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
